# -*- coding: utf-8 -*-
"""Upload_Local File Forward Google Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1csBCUgh-IDssBLkEk_EjgMDw4wlBzC6b
"""

# Google Colab에 로그인하여 인증 받기
from google.colab import drive
drive.mount('/content/gdrive')

# 파일 업로드 함수 정의
def upload_file_to_colab(file_path, colab_path):
    from google.colab import files

    # 로컬 파일을 Colab으로 업로드
    files.upload()

    # 업로드된 파일을 지정된 경로로 이동
    import os
    file_name = os.path.basename(file_path)
    uploaded_file_path = list(files.upload())[0]
    shutil.move(uploaded_file_path, colab_path)
    print(f"Uploaded '{file_path}' to Colab: '{colab_path}'")

# 로컬 환경의 파일 경로와 Colab에 업로드할 경로 지정
local_file_path = r"C:\Users\USER\OneDrive\file.txt"
colab_file_path = "/content/gdrive/MyDrive/file.txt"

# 파일 업로드 함수 호출
upload_file_to_colab(local_file_path, colab_file_path)